name: Baedeker

on:
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours
  workflow_dispatch:  # Allows manual dispatch
  push:
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update &&
        sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

    - name: Install Rust 
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        components: rustfmt
        profile: minimal

    - name: Clone Baedeker repository
      run: |
        git clone https://github.com/UniqueNetwork/baedeker.git
        cd baedeker
        cargo build --release
        sudo cp ./target/release/baedeker /usr/local/bin
        sudo chmod +x /usr/local/bin/baedeker

    - name: Create chain spec and secrets
      run: |
        sudo ./baedeker/up.sh ./baedeker/forkless-data.jsonnet --tla-str=forked_spec=subtensor --tla-str=fork_source=wss://entrypoint-finney.opentensor.ai

    - name: Upload chain spec and secrets as artifact
      uses: actions/upload-artifact@v2
      with:
        name: baedeker-config
        path: |
            baedeker/.bdk-env/specs/subtensor.json
            baedeker/.bdk-env/secrets